@startuml Diagrama_Casos_De_Uso_Autenticacion

top to bottom direction
skinparam packageStyle rectangle
skinparam shadowing false
skinparam actorStyle awesome

actor "Usuario / Docente" as Usuario
actor "Administrador" as Admin

rectangle "Módulo de Login y Autenticación" {
    usecase "CU-01: Ingresar Cédula" as CU_IngresarCedula
    usecase "CU-02: Validar Cédula" as CU_ValidarCedula
    usecase "CU-03: Verificar Rol por Cédula" as CU_VerificarRol
    usecase "CU-04: Seleccionar Modo de Acceso" as CU_SeleccionarModo
    usecase "CU-05: Autenticar Administrador" as CU_AutenticarAdmin
    usecase "CU-06: Acceder a Encuesta" as CU_AccederEncuesta
    usecase "CU-07: Acceder a Panel de Administración" as CU_AccederPanel
}

Usuario --> CU_IngresarCedula
Admin --> CU_IngresarCedula

CU_IngresarCedula ..> CU_ValidarCedula : <<include>>
CU_IngresarCedula ..> CU_VerificarRol : <<include>>

CU_VerificarRol ..> CU_AccederEncuesta : <<extend>> \n (Si es Usuario Regular)
CU_VerificarRol ..> CU_SeleccionarModo : <<extend>> \n (Si es Administrador)

CU_SeleccionarModo ..> CU_AccederEncuesta : <<extend>> \n (Elige Encuesta)
CU_SeleccionarModo ..> CU_AutenticarAdmin : <<extend>> \n (Elige Panel Admin)

CU_AutenticarAdmin ..> CU_AccederPanel : <<include>>

@enduml
