name: Deploy Backend to Azure App Service

on:
  push:
    branches:
      - master # O el nombre de tu rama principal (ej. master)
    paths:
      - 'Backend/**' # Solo se ejecuta si cambian archivos del backend
  workflow_dispatch: # Permite ejecutar el workflow manualmente desde la pestaña Actions de GitHub

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GitHub Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm'
          cache-dependency-path: './Backend/package-lock.json'

      - name: Install dependencies & Build (Compile TypeScript)
        working-directory: ./Backend
        run: |
          npm ci
          npm run build --if-present

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'semi-api' # Cambia por el nombre de tu App Service (ej. fecyt-backend-api)
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: './Backend' # Despliega la carpeta del backend compilada